### ISSUE TITLE
Neolink.toml?

### ISSUE THREAD

**Issue by IanK6449** [dm82m/hassio-addons#1]
Hi, 

Firstly thanks for putting an Addon together for Neolink... I am hoping it proves very useful for me.
I have a Reolink Argus Eco camera but not sure yet whether it will work with that.
I installed the addon but when starting the log states that the file neolink.toml could not be found:

[2022-10-30T06:07:42Z INFO  neolink] Neolink d75e416c96b9867875bc7252777302e8cec214ab release
Error: Failed to read "/config/addons/neolink.toml"
Caused by:
    No such file or directory (os error 2)

Does this mean I also need to install Neolink somewhere on my Raspberry Pi running HASSOS or should that have happened as part of the addon install? I have checked my /config directory via Samba and have no addons directory under that. I do have access to the /addons directory but that is currenty empty even though I have quite a few addons already installed.
 
I appreciate this is a very new addon (and I am pretty non-technical!) so may well have some teething trouble... any and all assistant is welcome.

Cheers,
IK

**Comment by dm82m** [comment]
You only need to place the neolink config into your home assistant configuration folder and there into the sub folder „addons“. So path would be /config/addons - file needs to be named neolink.toml 
Details about Neolink: https://github.com/thirtythreeforty/neolink

**Comment by IanK6449** [comment]
Thanks Dirk... very quick reply!
So, can I just download the code directly from Github for Neolink and place it all in the /config/adding directory or do I need to do something else with the code first?

Apologies for the noob questions!

IK

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dm82m** [comment]
No only the config file. All the rest is in my addon. But my addon does not know the address of your camera, your username and your password. So you need to tell it to my addon. That is done by the neolink config file. Start reading here: https://github.com/thirtythreeforty/neolink#configuration

**Comment by IanK6449** [comment]
OK, will give that a whirl. Thanks Dirk :-)

**Comment by dm82m** [comment]
Let me know how how it went

**Comment by IanK6449** [comment]
Hey Dirk,

Thanks for your help, I did get it working in the end 😊
Once I got the config file right (the address was a UID not an IP address) it worked straight away.
Thanks very much for making this addon available… I really appreciate it!

**Comment by dm82m** [comment]
thanks for your feedback!

**Comment by IanK6449** [comment]
Hi Dirk,

Apologies but I didn’t want to raise this as an issue for your Addon as it isn’t really.
But, the Neolink addon you very kindly created uses the official version of Neolink that, as far as I know, doesn’t support the stream pause functions as outlined in this neolink fork?:
https://github.com/QuantumEntangledAndy/neolink

I can’t really tell if this has been included in the master version of Neolink but I suspect not as, even with the relevant stream pause entries in my config.toml, I am still seeing very high battery drain.
So, I suspect the config entries I have added aren’t actually doing anything.

So, would it be possible please to make an addon that uses this fork of Neolink instead please?
I would actually quite like to make my own addon so am happy to take a stab at that if you have any decent references you could point me towards?
It’s about time I started doing something like this but I currently have no clue how to take a set of github code and make it into an addon.

Thanks for your time either way,

IK

**Comment by dm82m** [comment]
I didn’t see any pause command or feature in this fork. Can you point me to it? Would be no problem to switch to this fork or even create a second plug-in for this fork.

**Comment by IanK6449** [comment]
It’s at this Github link: https://github.com/QuantumEntangledAndy/neolink/blob/motion_stream/.github/workflows/docker.yml
But I don’t know if this is still a valid link and I have no idea how to check that sorry.
I did try to edit your original addon files and switch the nightly.links links to this build… but I couldn’t find the right workflow action (I think) to get the github nightly link from.

Cheers,

IK

**Comment by dm82m** [comment]
Please point me to the pause function. Where is it and how is it configurable?

**Comment by IanK6449** [comment]
It’s referenced in this thread and the code appears to be at the github link but beyond that I know next to nothing.
https://github.com/thirtythreeforty/neolink/issues/204

I have asked the guy who made the fork whether it has been rolled into the main code yet but am awaiting his response.

IK

**Comment by dm82m** [comment]
As far as I read it’s not functioning. And it is also not integrated in any master branch of the Neolink repos. Let’s wait what they will reply on your question there.

**Comment by IanK6449** [comment]
Thanks Dirk. Yeah OK, let’s wait and hope this capability gets rolled into a master branch of Neolink one day.
I’ll add my voice to the polite petitions for it 😊

IK
