### ISSUE TITLE
Trying to install the Neolink Addon and get this error

### ISSUE THREAD

**Issue by stoniwankenobii** [dm82m/hassio-addons#10]
Failed to install add-on

The command '/bin/bash -o pipefail -c wget https://nightly.link/thirtythreeforty/neolink/workflows/build/master/release-arm64-buster.zip' returned a non-zero code:8

I have had the addon installed before not sure if that could cause an issue as well.

**Comment by dm82m** [comment]
Seems that the url changed, will have a look on Saturday and let you know.

**Comment by dm82m** [comment]
https://github.com/thirtythreeforty/neolink/issues/351

**Comment by dm82m** [comment]
Will need to switch the version

**Comment by stoniwankenobii** [comment]
Also while searching for your repo after not starring it before I found this new fork that could be useful especially with Home Assistant

[https://github.com/QuantumEntangledAndy/neolink](url)

**Comment by dm82m** [comment]
Yes also found that, will switch to this

**Comment by QuantumEntangledAndy** [comment]
(Came from the linked issue)

Looking at your dockerfile is there any reason you don't use something like

```dockerfile
FROM quantumentangledandy/neolink:latest
```

To start off the image. Then I think all you'll need is your run.sh

This fork has multi arch docker support so it should work for all your arch

**Comment by dm82m** [comment]
Could be possible yes, I had a reolink cam for about a week and created that addon. Never looked to deep. Will think about switching to Andy’s fork and check if it is possible to directly use his image.

**Comment by dm82m** [comment]
@QuantumEntangledAndy if I try to use your docker image I end up with:

`/entrypoint.sh: 9: /entrypoint.sh: /run.sh: not found`

if I try to use your binaries (instead of thirtythreefourty) I end up with:

```
neolink_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by neolink_amd64)
neolink_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by neolink_amd64)
neolink_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by neolink_amd64)
```

**Comment by dm82m** [comment]
you can find both approaches on the repo in branches andy-docker and andy-binary

**Comment by QuantumEntangledAndy** [comment]
Ok, both are rather quick to fix I've detailed them in  #11 and make a PR against the `andy-docker` branch that should fix it.

**Comment by dm82m** [comment]
@stoniwankenobii can you please try 0.0.4 and reply if it works for you - we switched to the fork of Andy.

@QuantumEntangledAndy thanks for your quick help; your docker image is working on my amd64 host.

**Comment by dm82m** [comment]
@QuantumEntangledAndy can you confirm, that your docker image runs with all the arch that my container was running before: AARCH64, AMD64, ARMHF, ARMV7, I386. And does your multi arch support gives support to even more archs?

**Comment by stoniwankenobii** [comment]
> @stoniwankenobii can you please try 0.0.4 and reply if it works for you - we switched to the fork of Andy.
> 
> @QuantumEntangledAndy thanks for your quick help; your docker image is working on my amd64 host.

Installed and got it up and running. Will get the camera added tomorrow.

**Comment by QuantumEntangledAndy** [comment]
We build it for linux/amd64,linux/arm/v7,linux/arm64,linux/386

so the 32/64bit x86 and the 32/64 bit arms (hardware floats)

**Comment by dm82m** [comment]
@stoniwankenobii please be aware: if you want to use the newest features of andys fork you ne to rebuild my HA addon so that it forces to use the newest image provided by Andy.

**Comment by dm82m** [comment]
@stoniwankenobii I updated to 0.0.5 to support mqtt mode aswell, find details here: https://github.com/dm82m/hassio-addons/issues/12

**Comment by QuantumEntangledAndy** [comment]
Just thought I'd point out that the mqtt is in a bit of a odd state at the moment. I recently switched to a green thread model (helped reduce cpu among other things) and I haven't fully finished upgrading the mqtt to use it yet
