### ISSUE TITLE
How do I enable MQTT for Neolink?

### ISSUE THREAD

**Issue by kohkohwastaken** [dm82m/hassio-addons#12]
Cant see where I should be putting ./neolink mqtt --config=neolink.toml to enable MQTT?

**Comment by dm82m** [comment]
@kohkohwastaken please update to 0.0.5 and select `mqtt` within the addon configuration.

**Comment by dm82m** [comment]
@kohkohwastaken please keep that in mind: https://github.com/dm82m/hassio-addons/issues/10#issuecomment-1510172039
