### ISSUE TITLE
Argus 2 neolink

### ISSUE THREAD

**Issue by Blackspell01** [dm82m/hassio-addons#16]
Hey, I successfully installed your addon and set up the neolink.toml file with my uids. The log shows the following:

>  --- Neolink ---
> [2023-06-23T16:13:47Z INFO  neolink] Neolink 254a310fe9e9a9516a1a72e634074781aa23f780 release
> [2023-06-23T16:13:47Z INFO  neolink::rtsp] Starting RTSP Server at 0.0.0.0:8554
> [2023-06-23T16:13:47Z INFO  neolink_core::bc_protocol] entry: Trying local discovery
> [2023-06-23T16:13:47Z INFO  neolink_core::bc_protocol] garden: Trying local discovery
> [2023-06-23T16:13:52Z INFO  neolink_core::bc_protocol] garden: Trying remote discovery
> [2023-06-23T16:13:52Z INFO  neolink_core::bc_protocol] entry: Trying remote discovery
> [2023-06-23T16:13:52Z INFO  neolink_core::bc_protocol] garden: Trying map discovery
> [2023-06-23T16:13:53Z INFO  neolink_core::bc_protocol] entry: Trying map discovery
> [2023-06-23T16:13:57Z INFO  neolink_core::bc_protocol] garden: Trying relay discovery
> [2023-06-23T16:13:59Z INFO  neolink_core::bc_protocol] entry: Trying relay discovery
> [2023-06-23T16:13:59Z INFO  neolink_core::bc_protocol] garden: Relay success 952700008YPH7WNS at 20.113.39.145:55202
> [2023-06-23T16:13:59Z INFO  neolink_core::bc_protocol] entry: Relay success 95270000ATD9484H at 20.113.39.145:51000
> [2023-06-23T16:14:00Z WARN  neolink::rtsp] entry: Retryable error: entry: Could not login to camera
> Caused by:
> 0: IO Error: Custom { kind: Other, error: CameraTerminate }
> 1: Camera terminated the connection
> [2023-06-23T16:14:00Z INFO  neolink_core::bc_protocol] entry: Trying local discovery
> [2023-06-23T16:14:00Z INFO  neolink::rtsp::states::loggedin] garden: Camera time is already set: 2023-06-23 18:14:03.0 -01:00:00
> [2023-06-23T16:14:00Z INFO  neolink::rtsp::states::loggedin] garden: Camera reports firmware version 1221_246_237_22
> [2023-06-23T16:14:00Z INFO  neolink::rtsp::states::streaming] garden: Starting video stream Sub Stream (Fluent)
> [2023-06-23T16:14:00Z INFO  neolink::rtsp::states::streaming] garden: Starting video stream Main Stream (Clear)
> [2023-06-23T16:14:05Z INFO  neolink_core::bc_protocol] entry: Trying remote discovery
> [2023-06-23T16:14:05Z INFO  neolink_core::bc_protocol] entry: Trying map discovery
> [2023-06-23T16:14:10Z INFO  neolink_core::bc_protocol] entry: Trying relay discovery
> [2023-06-23T16:14:12Z INFO  neolink_core::bc_protocol] entry: Relay success 95270000ATD9484H at 20.113.39.145:53016
> [2023-06-23T16:14:13Z INFO  neolink::rtsp::states::loggedin] entry: Camera time is already set: 2023-06-23 18:14:12.0 -01:00:00
> [2023-06-23T16:14:13Z INFO  neolink::rtsp::states::loggedin] entry: Camera reports firmware version 1221_246_237_22
> [2023-06-23T16:14:13Z INFO  neolink::rtsp::states::streaming] entry: Starting video stream Main Stream (Clear)
> [2023-06-23T16:14:13Z INFO  neolink::rtsp::states::streaming] entry: Starting video stream Sub Stream (Fluent)
> [2023-06-23T16:14:54Z INFO  neolink::rtsp] garden: Buffers prepared
> [2023-06-23T16:15:05Z INFO  neolink::rtsp] entry: Buffers prepared
> 
> 

My problem is, that I cant create a generic camera, it just times out.

**Comment by dm82m** [comment]
This is an neolink issue, please open an issue there. It is unrelated to this addon. My addon only provided neolink.

https://github.com/QuantumEntangledAndy/neolink/issues
