### ISSUE TITLE
Bigger delay using version 0.0.8

### ISSUE THREAD

**Issue by Sinnedterklaas** [dm82m/hassio-addons#21]
After installation of the 0.0.8 update I notice a much bigger delay in camera footage. With the 0.0.7 version the delay is 2-3 seconds compared to the time stamp from the camera - with the 0.0.8 update it was around 15 seconds. Using it with a Lumus camera in combination with Frigate on HA.

**Comment by dm82m** [comment]
Pretty sure it has to do with Neolink and not the addon, please file an issue at @QuantumEntangledAndy Neolink repo.

**Comment by DanielB1982** [comment]
Hi. I have the same problem with 0.0.8
The RAM usage increases steadily and then the addon crashes 
0.0.8 uses neolink 0.6.3-rc.1, which version was used for 0.0.7 ?

I switched to a new thin client and can not restore my old neolink addon backup

**Comment by dm82m** [comment]
Everting you rebuild/reinstall my addon here it uses the „latest“ version of Neolink. So maybe try reinstalling it. Otherwise create an issue at @QuantumEntangledAndy repo and report the issue there.

**Comment by dm82m** [comment]
Will Set a concrete version instead of latest tomorrow. This then will result in the need to update this plugin whenever a new release is made.

**Comment by dm82m** [comment]
For the moment we switched to old 0.6.2, let’s see when Andy releases the next version and decide what we do
