### ISSUE TITLE
possability to set release version

### ISSUE THREAD

**Issue by si458** [dm82m/hassio-addons#23]
it would be nice to set which version to use or use a FIXED version not RC version!

as i currently have an issue where 0.6.3-rc1 doesnt work and keeps disconnecting but 0.6.2 works no problems!

https://github.com/QuantumEntangledAndy/neolink/issues/186

i cant rollback either because the dockerfile uses `latest` so builds on the fly which just happens to be the release canditate version

**Comment by dm82m** [comment]
#21 already addresses that

**Comment by si458** [comment]
that doesnt really fix my issue tho, i wanted the `dockerfile` changed to use a set version rather than latest,
then when a new release happens, just update your repo!

**Comment by dm82m** [comment]
This is what I will do tomorrow. Or you set a pull request for it and set version 0.6.2 manually and increase version to next within two files. Then i can merge it directly…

**Comment by dm82m** [comment]
For the moment we switched to old 0.6.2, let’s see when Andy releases the next version and decide what we do
