### ISSUE TITLE
No longer have config directory

### ISSUE THREAD

**Issue by Caddyman68** [dm82m/hassio-addons#29]
Somewhere somehow my "config" directory was renamed to "homeassistant" so the addon gives "Error: Failed to read "/config/addons/neolink.toml". Funny, but it still comes up as config when I SSH to it on the network. Tried everything I can in HA (rename - no, add new config - no). Someone online said it was done by Home Assistant in an update, but I can't imagine why and when and that there aren't others having this problem or similar with something else that is directed to the config directory (which is now homeassistant). I see the entries with that path in the run.sh file. I would attempt to fork the Git (or whatever) but that is beyond my capabilities anyway. Too bad - looks like I would've liked it.

Edit: Found out that an HA update back in November instituted this change. Part of what I read says "There is now a better solution for add-on developers. Add-ons can include addon_config in the list of folders to map. Then, the supervisor will create a folder for that add-on at /addon_configs/<your addon slug> and map that to /config within the add-on container. If your addon needs to be able to create and modify files in this folder in addition to collecting files from users, use addon_config:rw instead." The full article is here: https://developers.home-assistant.io/blog/2023/11/06/public-addon-config/?_highlight=addon_configs#new-addon_configs-folder. It would be great if you feel inclined to either change the code and/or make a revised version for those of us with current versions of HA. Thanks again

**Comment by dm82m** [comment]
@Caddyman68 it will work out of the box if you follow the documentation. 

my addons currently default to map config, thus my addons are getting the /homeassistant folder mappend into the addon. so if you put the neolink.toml into /homeassistant/addons/neolink.toml the addon should work as expected.

and I also reproduced it right now and can confirm that it works with the latest home assistant version.

**Comment by Caddyman68** [comment]
A user pointed that out in a forum. I somehow didn't place an addon folder in the homeassistant (config) directory and I guess just put the toml file ... God knows where. If only I had just SSHed in where the homeassistant directory was still named config. I was confusing myself with the file editor. All good now and I do like it. I would've just deleted my issue, but didn't see that option and also wanted to be sure you - as a developer - were aware of the new "solution". Thank you for taking the time to help and also for the great add on
