### ISSUE TITLE
Neolink Talk HA integration?

### ISSUE THREAD

**Issue by Morphy99** [dm82m/hassio-addons#3]
Hi I see you have developed an addon for HASS OS which is great. Although I don't use this currently, I have it on docker on another machine. I was just wondering if there was any way to call a neolink talk script from this addon? I think it would need a HA integration though.

**Comment by dm82m** [comment]
What is a neolink talk script?

**Comment by Morphy99** [comment]
Talk is a command you can send to neolink to play audio clips from a camera: https://github.com/thirtythreeforty/neolink#additional-commands

The only way to trigger this currently is via CLI and I was just trying to figure a way to do it from Home Assistant.

**Comment by dm82m** [comment]
no idea to be honest. I will not plan to implement or do something in this direction as I am not using a reolink camera anymore. But feel free and raise a PR here.

**Comment by Morphy99** [comment]
No problem, just thought I'd check to see if anyone was doing something with it. I'll close as it's likely going to have to be an integration not an addon
