### ISSUE TITLE
How to create the config.js file?

### ISSUE THREAD

**Issue by MaartenDrenth** [dm82m/hassio-addons#31]
Could you explain in detail how to do this?

Create the configuration file named config.js in your HAOS /config/addons/ folder.

I do not know where to do this. Sorry.

**Comment by dm82m** [comment]
Hey Maarten,

1) you can run the json-live-data-server on its own, wherever you want OR you use the Add-on resol-vbus. The addon resol-vbus is only a wrapper to run json-live-data-server within the home Assistant ecosystem.

2) you need to create that file within the path specified. Just follow the documentation I wrote: https://github.com/dm82m/hassio-addons/tree/main/resol-vbus

There is also a sample config file. Use that and modifiy it for your needs.
Specific questions about configuration are better be placed here as they belong to the json-live-data-server as you already did: https://github.com/danielwippermann/resol-vbus/issues/100

The file needs to be placed onto your home Assistant system into the directory named. If you do not know how to do that, I strongly suggest to get more familiar with Home Assistant. https://www.home-assistant.io/docs/configuration/

Best,
Dirk

**Comment by MaartenDrenth** [comment]
Hi Dirk

Thanks.

I think indeed that my main problem is that I'm not familiair enough with
HA. 😟
Even going through all the explanations on github I just can't figure out
where I can find the /config/addons/ folder so I can update/create the
config file.

I'm using Home Assistant Core and Studio Code Server. If you have a golden
tip about where to find information about this it would be much appreciated.
As far as I can see now this is my only blockingpoint to continue. The
add-on, haccs and json dat server part are done... I think 🤨

Thanks!






Op wo 6 mrt 2024 om 16:13 schreef Dirk ***@***.***>:

**Comment by dm82m** [comment]
If you find the configuration.yaml in studio code server, just create the addons folder in the same location and put the config file into the addons folder

**Comment by MaartenDrenth** [comment]
thanks again

it "sounds" so easy but I realy do not iunderstand it at all 😣
Normally I can find some tutorials on Youtube or one of the forums but now
no examples at all.


[image: image.png]


[image: image.png]

Op wo 6 mrt 2024 om 18:17 schreef Dirk ***@***.***>:

**Comment by shayneoneill** [comment]
How does one actually access these folders? I cant find it in the menus and the HAOSS command line is utterly mysterious to me, and I say that as someone who was coding on BSD minicomputers in the 90s. It aint linux like I've ever seen.

**Comment by dm82m** [comment]
There are multiple ways, depending on the installation type you chosed:

In case you are using Home Assistant Core only, you could install HACS (https://hacs.xyz/docs/setup/download) and install a integration like this: https://github.com/htmltiger/config-editor-card

In case you are using Home Assistant OS, you could install the "File Editor" Addon: https://github.com/home-assistant/addons/tree/master/configurator
Or alternatively you could install the SSH Addon (https://github.com/hassio-addons/addon-ssh) and use a sshto connect to the HAOS instance and do the config by command line. Or use a graphical ftp client to modify the config files.
Or alternatively you could install the Studio Code Server Addon (https://github.com/hassio-addons/addon-vscode) to edit the files.

As I said earlier: you guys are missing some essential understanding of Home Assistant and all the stuff around. Its understandable to me that you then have difficulties to get everything up and running.
