### ISSUE TITLE
addon not working

### ISSUE THREAD

**Issue by davidcd13** [dm82m/hassio-addons#32]
addon cannot start (home assistant 2024.3) I get several errors:

Failed to call /addons/a14d3924_neolink/start -
Failed to call /store/repositories -
/addons/a14d3924_neolink/start return code 400
/store/repositories return code 400

**Comment by dm82m** [comment]
Works on my machine with HA 2024.3.0. please provide more details and logs of supervisor aswell as logs of addon.
