### ISSUE TITLE
Neolink v0.6.3-rc1

### ISSUE THREAD

**Issue by acseven** [dm82m/hassio-addons#33]
Hi,
Would it be possible to have the [0.6.3-rc1](https://github.com/QuantumEntangledAndy/neolink/releases/tag/v0.6.3.rc.1) release installed via the addon? Maybe via a UI configuration setting?
In any case, thank you for making this available

**Comment by dm82m** [comment]
It’s not possible to make a version selector via ui cause the base image of the addon differs. What I could do is providing a second addon. So one for the current final release and the second one for the latest release. Would that help?

**Comment by acseven** [comment]
Hi, yes that would be great!

**Comment by dm82m** [comment]
added neolink-latest. refresh your add-ons in HAOS, uninstall Neolink and install, configure and start Neolink-latest Add-on.

**Comment by acseven** [comment]
Just a heads up, using latest results in fetching the most recent repo version (in this case iterations of rc2), instead of the latest actual rc1 which is marked in [the github repo as pre-release](https://github.com/QuantumEntangledAndy/neolink/releases). The current version doesn't work properly due to ongoing changes, meaning it shouldn't be used. 

Can you modify the docker image tag to be the latest RC?
`quantumentangledandy/neolink:v0.6.3.rc.1`

[](https://hub.docker.com/r/quantumentangledandy/neolink/tags)

On the subject:
https://github.com/QuantumEntangledAndy/neolink/issues/236#issuecomment-2056998064

**Comment by dm82m** [comment]
Rc1 was having also heavy problems, due to this fact we switched back to 0.6.2. if we now use rc1 directly instead of latest (which is rc2 today and could be rc3 tomorrow) than that would not make anything better.

**Comment by acseven** [comment]
Ok, understood. It's a matter of trying to use a version that seems stable enough then.
