### ISSUE TITLE
Vbus-LAN-Adapter

### ISSUE THREAD

**Issue by ThinLizzie** [dm82m/hassio-addons#36]
Hallo,
ich habe unter homeassistant/config/addons die Datei config.js angelegt und die Vorlage für den Vbus-LAN-Adapter hineinkopiert und die IP-Adresse auf die des Adapters gesetzt.

Dann habe ich unter Einstellungen-Addons-Resol-Vbus nachgesehen, was im Protokoll steht - leider nichts.

Was mache ich bitte falsch?
VG

**Comment by ThinLizzie** [comment]
Anfängerfehler.
Dann steht da:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
cp: cannot stat '/config/addons/config.js': No such file or directory
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by dm82m** [comment]
Das Addons Verzeichnis muss im gleichen Ordner liegen in dem die Home Assistent configuration.yaml liegt

siehe auch: https://github.com/dm82m/hassio-addons/issues/31#issuecomment-1981389149

dann Server Neustart

**Comment by hoppel118** [comment]
Falls du nach einem Neustart deiner HAOS Umgebung mal bemerkst, dass du keine Daten mehr vom Resol VBUS LAN Adapter mehr empfängst, dann musst du Home Assistant Neustarten (nicht Rebooten), siehe hier:

https://github.com/dm82m/hass-Deltasol-KM2/issues/30#issuecomment-1488281159

**Comment by ThinLizzie** [comment]
![image](https://github.com/user-attachments/assets/4a2cbd68-657c-4fbc-b31d-2c92a0aad1b7)

Den addons-Ordner habe ich auch dort abgelegt:
![image](https://github.com/user-attachments/assets/3c961210-dfe1-462c-96f6-ad267fcf4509)

Und erhalte dann:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.7.0
npm version: 10.8.2
--- DEVICES ---
ls: cannot access '/dev/ttyUSB*': No such file or directory
ls: cannot access '/dev/ttyACM*': No such file or directory
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
info: Ready to serve from the following URLs:
info:     - http://127.0.0.1:3333/api/v1/live-data (internal)
info:     - http://172.30.33.2:3333/api/v1/live-data
debug: HeaderSet complete
debug: HeaderSet complete
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.7.0
npm version: 10.8.2
--- DEVICES ---
ls: cannot access '/dev/ttyUSB*': No such file or directory
ls: cannot access '/dev/ttyACM*': No such file or directory
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
info: Ready to serve from the following URLs:
info:     - http://127.0.0.1:3333/api/v1/live-data (internal)
info:     - http://172.30.33.2:3333/api/v1/live-data
debug: HeaderSet complete

Ist das das gewünschte Ergebnis?

**Comment by dm82m** [comment]
Ja.

jetzt diese Integration installieren und in der configuration.yaml konfigurieren. Dann Home Assistant Core neu starten.

https://github.com/dm82m/hass-Deltasol-KM2?tab=readme-ov-file#example-configurationyaml-1

**Comment by ThinLizzie** [comment]
Ist das so richtig in der configuration.yaml?
![image](https://github.com/user-attachments/assets/a430cb08-09ca-4a76-afbd-818c76fa1906)


Danach werden 115 Entitäten, aber ohne Werte im Zustand angezeigt.
Kommt mir nicht richtig vor.

**Comment by dm82m** [comment]
Wenn du in der configuration.yaml sonst keine sensor Definition hast dann passt das so. Darfst halt nicht zwei Sensor: Definitionen haben

**Comment by ThinLizzie** [comment]
Und wo kann man nun die Werte sehen?
Ich habe einen Deltasol BX plus hinter dem Interface im Einsatz.

**Comment by dm82m** [comment]
Aber ein paar Sensoren sollten schon werte anzeigen. Aktivier mal debug logging für die Integration und poste das hier.

**Comment by dm82m** [comment]
@hoppel118 zeigt der RESOL Vbus bei dir im adding log mehr an?

**Comment by ThinLizzie** [comment]
Im "Verlauf" steht gar nichts zu dieser Entität.

**Comment by dm82m** [comment]
Verlauf ist nicht die richtige Stelle, schau dir die Entitäten an, zb sensor.temperature_sensor_1

**Comment by ThinLizzie** [comment]
Verstehe. Das sieht gut aus!
Jetzt muss man nur noch die relevanten Entitäten benennen und dann kann der Spaß beginnen.
Vielen Dank!

**Comment by ThinLizzie** [comment]
Eine Zusatzfrage bitte noch: Gibt es eine Vorlage für so eine tolle Visualisierung, die man im Netz sehen kann?

**Comment by dm82m** [comment]
Vorlage brauchst Du dazu keine. Du kannst das einfach mit Home Assistant machen:

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/62955056-dca5-4368-b517-024f704f1a4f">

Lovelace Dashboard:
```
entities:
  - entity: sensor.temperature_sensor_1
    name: Kollektortemperatur
  - entity: sensor.temperature_sensor_2
    name: Puffertemperatur
  - entity: sensor.hot_water_temperature
    name: Warmwassertemperatur
  - entity: sensor.pump_speed_relay
    name: Pumpe Relais
hours_to_show: 24
refresh_interval: 0
type: history-graph
```

**Comment by ThinLizzie** [comment]
Das geht ja sehr einfach und gut.

Gibt es für so etwas eine Vorlage-wie zB für Wechselrichter:
![210336617-76db504e-8c1b-492a-8d2f-a32123d1837d](https://github.com/user-attachments/assets/2d8ead58-1ddd-439a-9f85-da5db043a497)

**Comment by dm82m** [comment]
ich verwende keine, out-of-the-box glaube ich eher nicht, kannst du dir aber auch mit templates selber bauen
