### ISSUE TITLE
Installation fail with unknown manifest

### ISSUE THREAD

**Issue by Senbei123** [dm82m/hassio-addons#38]
Hi,

I can't install the plugin "neolink". I directly get "manifest for quantumentangledandy/neolink:v0.6.2 not found: manifest unknown: manifest unknown".

The installation of "neolink-latest" work.

KR,
Tristan

**Comment by dm82m** [comment]
@QuantumEntangledAndy your docker image got deleted, can you investigate and re-build and release 0.6.2?

**Comment by QuantumEntangledAndy** [comment]
Ah my docker prune script accidentally cleaned up the version tags (regex filter was incorrect). I'll have to rebuild and push them

**Comment by QuantumEntangledAndy** [comment]
So fun times ToT, tried to just rebuild the old tags and the toolchain is giving me this

```rust
= note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
For more information about this error, try `rustc --explain E0282`.
```

Which would mean it would be a lot of work on my end to go to each commit fix the builds then rebuild then push to github actions to build all the images on the different hardware then push to dockerhub

**Comment by QuantumEntangledAndy** [comment]
I'm working on a workaround, I should be able to build arbitary versions in a new workflow but it may not be exactly the same since it will use the newer base container images

**Comment by QuantumEntangledAndy** [comment]
I got 0.6.1 to rebuild I'll try and get all the others soon too

**Comment by dm82m** [comment]
Greetings to the prune script and more greetings to regex magic 😂😂😂

thanks for your work, you can also just release the new 0.6.3 and we all forget 0.6.2 🤪

**Comment by QuantumEntangledAndy** [comment]
I just for loops all the tags. They are all being rebuilt tonight. I'll check back in he morning (it's late here)

**Comment by QuantumEntangledAndy** [comment]
Just checked and its already done. So all tags are up and running once more (also fixed my prune script)

**Comment by dm82m** [comment]
Thanks Andy!

@Senbei123 it is back working, just installs the addon.
