### ISSUE TITLE
Reolink flood light push issue

### ISSUE THREAD

**Issue by mgirgenti** [dm82m/hassio-addons#39]
NeoLink-Latest installed on:
Core	2024.11.2
Supervisor	2024.11.3
Operating System	13.2
Frontend	20241106.2

Config file created and working.  Upon start, Neolink finds the floodlight from the config, logs in, verifies, time, etc.  All good with connection. MQTT looked to connect.  If I use a bad MQTT password, I get the expected connection errors.  

With correct password, I start getting this error:

neolink::common::pushnoti] Issue connecting to push notifications server: Http(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })

Is this an HA, issue, Neolink issue, or Reolink FL issue?

**Comment by dm82m** [comment]
I would assume neolink and suggest creating an issue there.

**Comment by mgirgenti** [comment]
Thanks. Submitted.

**Comment by dm82m** [comment]
if you want you can link the issue to this one here, for further people with the same question. I will close it here.
