### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by zauan** [dm82m/hassio-addons#5]
Hi there,

I tried to install this addon, however, it doesn't seem to work anymore:

```The command '/bin/bash -o pipefail -c wget https://nightly.link/thirtythreeforty/neolink/workflows/build/master/release-ubuntu-18.04.zip' returned a non-zero code: 8```

from what I see, the neolink download URL for ubuntu changed to https://nightly.link/thirtythreeforty/neolink/workflows/build/master/release-ubuntu-20.04.zip

Best regards,
Stefan

**Comment by dm82m** [comment]
thanks for reporting, should be fixed, just reload the addon and rebuild it. should be version 0.0.2 now.

**Comment by zauan** [comment]
Thanks!

was about to make a pull request just now :))
