### ISSUE TITLE
Unable to use MQTT // logs showing "undefined" as port for the live data URL's

### ISSUE THREAD

**Issue by thwandi** [dm82m/hassio-addons#9]
Hi,

I have installed this Addon and as far as I can tell (LED on the VBUS Lan adapter starts blinking) it is connecting to the lan adapter as expected.

I am unable to get any data to my MQTT server or into the hass-Deltasol-KM2 HACS addon.

Here is the relevant output of the log:

--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
info: Ready to serve from the following URLs:
info:     - http://127.0.0.1:undefined/api/v1/live-data (internal)
info:     - http://172.30.33.4:undefined/api/v1/live-data

Could you give me some direction here? I have filled out the MQTT data in the config.js file, I have left '' for user and password as I don't have that on my server. 

Thank you!

**Comment by dm82m** [comment]
Use the example config.ja file and only change the ip to the one your vbus/lan is using. Leave the rest as it is and restart the addon.

**Comment by thwandi** [comment]
Okay, that worked for the HACS addon. I was under the Impression that there is no difference to the config.js from Daniel.

Is there a way to enable the MQTT data pushing in yours?

**Comment by dm82m** [comment]
Never used mqtt. You can use my integration to access the json-live-data-server and get the data into home assistant.
